// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToInstances = new Map<string, string>();
contractsToInstances.set("0xda2f062f9643e907da4ee71d32e67e6f97b4e827", // Instance-bnb-0.1
  "bnb-0.1"
);
contractsToInstances.set("0xda2f062f9643e907da4ee71d32e67e6f97b4e827", // Instance-bnb-1
  "bnb-1"
);
contractsToInstances.set("0xda2f062f9643e907da4ee71d32e67e6f97b4e827", // Instance-bnb-10
  "bnb-10"
);
contractsToInstances.set("0xda2f062f9643e907da4ee71d32e67e6f97b4e827", // Instance-bnb-100
  "bnb-100"
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
